--INITIALISATION TABLE ROLE
INSERT INTO ROLE (ROLE_ID,ROLE_NAME) VALUES (1,'ROLE_ADMIN');
INSERT INTO ROLE (ROLE_ID,ROLE_NAME) VALUES (2,'ROLE_USER');

--INITIALISATION TABLE USER
INSERT INTO USER (USER_ID, USERNAME, PASSWORD, ENABLED) values (100000, 'admin', '$2a$10$czkxax6uc4B.TmL8FsKRxebC5ObunTu8AeuSLE1sb0gSOGtIeMTgS', true);
INSERT INTO USER (USER_ID, USERNAME, PASSWORD, ENABLED) values (100001, 'user', '$2a$10$2Yz9VONGnnz3doggkOQE5u9hK1c5YnN1VFx.koa7r5WJlyzcSxHWK', true);

-- JOINT TABLE
INSERT INTO USER_ROLES(USER_ID,ROLE_ID) VALUES (100000,1);
INSERT INTO USER_ROLES(USER_ID,ROLE_ID) VALUES (100000,2);
INSERT INTO USER_ROLES(USER_ID,ROLE_ID) VALUES (100001,2);

COMMIT;